version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: my_mongodb
    networks:
      - my_network

  express:
    image: llleeemh/uxagent-backend
    container_name: my_express
    ports:
      - "3000:3000"
    networks:
      - my_network

  frontend:
    image: llleeemh/uxagent-frontend
    container_name: my_frontend
    ports:
      - "8080:80"
    networks:
      - my_network

networks:
  my_network:
